Repository jameshughes89/cs102, pull requests merged in 2021-06, with the labels that each got.

#83 :memo: :lipstick: Remove suggestion to use emojis in body of issues and PRs
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#87 :bug: correct link to `CONTIBUTING` in templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug/typo

#86 :lipstick: specify "related" for issues/prs in templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: formatting

#88 :memo: Update and change emojies to correspond to labels
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation --- memo :memo:

#84 :new: :mortar_board: Topic9 Introduction and Time Complexity Sections
  src/site/img/complexity_growth0.png
  src/site/img/complexity_growth1.png
  src/site/img/complexity_linear.png
  src/site/img/complexity_quadratic.png
  src/site/img/complexity_table.png
  src/site/topic9.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#90 :memo: Change :baby: to :medal_sports: for "good first issue" label
  CONTRIBUTING.md
Labels: documentation --- memo :memo:

#92 :mortar_board: Topic9 Add section on growth functions
  src/site/conf.py
  src/site/topic9.rst
Labels: content --- mortar_board :mortar_board:

#95 :mortar_board: Topic9 Add section showing examples of derriving t(n)
  src/site/topic9.rst
Labels: content --- mortar_board :mortar_board:

#91 :memo: Add link to CONTRIBUTING to the README page
  README.md
Labels: documentation --- memo :memo:

#97 :mortar_board: Topic9 Add an aside for amortization
  src/site/img/complexity_amortization0.png
  src/site/img/complexity_amortization1.png
  src/site/topic9-amortized.rst
  src/site/topic9.rst
Labels: content --- mortar_board :mortar_board:

#94 :mortar_board: Topic9 Add asymptotic growth Section
  src/site/topic9.rst
Labels: content --- mortar_board :mortar_board:

#98 :mortar_board: Topic10 Add introductory section
  src/site/img/queue.png
  src/site/img/queue_add.png
  src/site/img/queue_remove.png
  src/site/topic10.rst
Labels: content --- mortar_board :mortar_board:

#99 :mortar_board: Topic10 Add section on queue operations
  src/site/topic10.rst
Labels: content --- mortar_board :mortar_board:

#101 :new: :mortar_board: Topic10 Add the queue interface to the repo
  src/main/java/Queue.java
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#102 :mortar_board: Topic10 Add Queue interface to the topic page
  src/site/topic10.rst
Labels: content --- mortar_board :mortar_board:

#104 :mortar_board: :lipstick: :art: :telescope: Change sizes of images
  src/site/topic10.rst
  src/site/topic6-testing.rst
  src/site/topic7.rst
  src/site/topic8-nested.rst
  src/site/topic8.rst
  src/site/topic9.rst
Labels: art :art:, consistency --- telescope :telescope:, content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#105 :mortar_board::new: Topic11 Introduction section
  src/site/topic11.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#108 :bug: :mortar_board: Topic8 Typo in comment for playing code
  src/site/topic8.rst
Labels: typo/bug :bug:

#111 :new: :mortar_board: Topic11 Section on enqueuing
  src/site/topic11.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#110 :new: :mortar_board: Topic11 LinkedQueue implementation with LinkedQueueTest
  src/main/java/LinkedQueue.java
  src/test/java/LinkedQueueTest.java
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#113 :new: :mortar_board: Topic11 Section on priority queues
  src/site/topic11.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#114 :telescope: :mortar_board: Change `EmptyStackException` to `NoSuchElementException` for stacks
  src/main/java/ArrayStack.java
  src/main/java/LinkedStack.java
  src/site/topic6.rst
  src/site/topic8-nested.rst
  src/site/topic8.rst
  src/site/topic9.rst
  src/test/java/ArrayStackTest.java
  src/test/java/LinkedStackTest.java
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#112 :new: :mortar_board: Topic11 Dequeueing and first section
  src/site/topic11.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#116 :telescope: :bug: Update `if`/`else` statements
  src/main/java/ContactList.java
  src/site/topic11.rst
  src/site/topic3.rst
Labels: consistency --- telescope :telescope:, typo/bug :bug:

#117 :new: :mortar_board: Topic11 Add playing code
  src/site/topic11.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#118 :telescope: :mortar_board: Topic8 Move playing code to the end of the page
  src/main/java/LinkedQueue.java
  src/site/topic11.rst
  src/site/topic8.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#119 :lipstick: :mortar_board: Topic11 Add relevant questions about complexity
  src/site/topic11.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#120 :telescope: :lipstick: Use `initialCapacity` for `ArrayStack` constructor
  src/main/java/ArrayStack.java
Labels: consistency --- telescope :telescope:, formatting --- lipstick :lipstick:

#121 :bug: :lipstick: :telescope: Remove extra \n at end of `toStrings` for data structures
  src/main/java/ArrayStack.java
  src/main/java/LinkedQueue.java
  src/main/java/LinkedStack.java
  src/site/topic6.rst
  src/site/topic8.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:, typo/bug :bug:

#122 :new: :mortar_board: Topic12 `ArrayQueue` and `ArrayQueueTest` code added to repo
  src/main/java/ArrayQueue.java
  src/test/java/ArrayQueueTest.java
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#123 :mortar_board: Remove line numbers from playing code for easy copy/paste
  src/site/topic11.rst
  src/site/topic3.rst
  src/site/topic6.rst
  src/site/topic8.rst
Labels: content --- mortar_board :mortar_board:

#124 :memo: Add note to templates on Where heading
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation --- memo :memo:

#125 :new: :mortar_board: Topic12 Intro section
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#127 :new: :mortar_board: Topic12 Add idea2 section
  src/site/img/arrayqueue_2idea0.png
  src/site/img/arrayqueue_2idea1.png
  src/site/img/arrayqueue_2idea2.png
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#128 :new: :mortar_board: Topic12 Start idea 3 content
  src/site/img/arrayqueue_3idea0.png
  src/site/img/arrayqueue_3idea1.png
  src/site/img/arrayqueue_3idea2.png
  src/site/img/arrayqueue_circle0.png
  src/site/img/arrayqueue_circle1.png
  src/site/img/arrayqueue_circle2.png
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#130 :new: :mortar_board: Topic12 Modulo subsection for idea #3
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#126 :new: :mortar_board: Topic12 Add idea1 section
  src/site/img/arrayqueue_1idea0.png
  src/site/img/arrayqueue_1idea1.png
  src/site/img/arrayqueue_1idea2.png
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#132 :new: :mortar_board: Topic12 Add section on implementation
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#133 :new: :mortar_board: Topic12 Add testing section
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#141 :new: :mortar_board: Topic13/14 Reorder topics
  src/site/topic13.rst
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#144 :new: :mortar_board: Topic12 Aside on `expandCapacity` for `ArrayQueue`
  src/site/img/arrayqueue_expand_why.png
  src/site/topic12-expand.rst
  src/site/topic12.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#151 :bug: :mortar_board: fix empty stack exception messages
  src/main/java/ArrayStack.java
  src/main/java/LinkedStack.java
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#145 :new: :mortar_board: Topic16 Introduction
  src/site/img/exceptions.png
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#148 :new: :mortar_board: Topic16 Section on throwing exceptions
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#146 :new: :mortar_board: Topic16 Error section
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#142 :new: :mortar_board: Topic13 List interfaces
  src/main/java/IndexedList.java
  src/main/java/List.java
  src/main/java/SortedList.java
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#152 :new: :memo: :telescope: Add language formatter
  .editorconfig
  CONTRIBUTING.md
  README.md
  build.gradle
  src/main/java/ArrayQueue.java
  src/main/java/ArrayStack.java
  src/main/java/ContactList.java
  src/main/java/Friend.java
  src/main/java/LinkedQueue.java
  src/main/java/LinkedStack.java
  src/main/java/Node.java
  src/main/java/Queue.java
  src/main/java/Stack.java
  src/site/conf.py
  src/site/index.rst
  src/test/java/LinkedQueueTest.java
  src/test/java/LinkedStackTest.java
Labels: consistency --- telescope :telescope:, documentation --- memo :memo:, enhancement/new :new:, formatting --- lipstick :lipstick:

#156 :lipstick: :telescope: Update try/catch statements
  src/site/topic11.rst
  src/site/topic12.rst
  src/site/topic6.rst
  src/site/topic8.rst
Labels: consistency --- telescope :telescope:, formatting --- lipstick :lipstick:

#150 :new: :mortar_board: Topic16 Small aside for implementing our own exception
  src/main/java/EmptyCollectionException.java
  src/site/topic16-create.rst
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#149 :new: :mortar_board: Topic16 Section on catching exceptions
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#147 :new: :mortar_board: Topic16 Section on Exceptions (checked and unchecked)
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#162 :mortar_board: Reorder iterator and exceptions topics
  src/site/topic16.rst
  src/site/topic17-create.rst
  src/site/topic17.rst
Labels: content --- mortar_board :mortar_board:

#163 :mortar_board: Topic13 Change List Interfaces to Bag Interfaces
  src/main/java/Bag.java
  src/main/java/IndexedBag.java
  src/main/java/List.java
  src/main/java/SortedBag.java
  src/main/java/SortedList.java
Labels: content --- mortar_board :mortar_board:

#164 :mortar_board: Topic13 Bag topic introduction
  src/site/topic13.rst
Labels: content --- mortar_board :mortar_board:

#166 :mortar_board: Topic13 SortedBag and IndexedBag subsections
  src/main/java/IndexedBag.java
  src/main/java/SortedBag.java
  src/site/img/bag_IndexedBag0.png
  src/site/img/bag_IndexedBag1.png
  src/site/img/bag_sortedBag0.png
  src/site/img/bag_sortedBag1.png
  src/site/topic13.rst
Labels: content --- mortar_board :mortar_board:

#165 :mortar_board: Topic13 Section for high level intro to bags
  src/site/img/bag_general0.png
  src/site/img/bag_general1.png
  src/site/topic13.rst
Labels: content --- mortar_board :mortar_board:

#171 :mortar_board: Topic13 Section for bag functionality
  src/main/java/Bag.java
  src/site/topic13.rst
Labels: content --- mortar_board :mortar_board:

#172 :mortar_board: Topic14 Add Terminology section
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#173 :mortar_board: Topic14 Add intro section for inheritance
  src/site/img/inheritance_bag.png
  src/site/img/inheritance_vehicle.png
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#174 :mortar_board: Topic14 Object section
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#176 :mortar_board: Topic14 Polymorphism section and binding subsection
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#177 :mortar_board: Topic14 Aside on inheriting problems
  src/site/img/inheritance_bad.png
  src/site/img/inheritance_rectangle.png
  src/site/img/inheritance_square.png
  src/site/topic14-careful.rst
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#175 :mortar_board: Topic14 Collections and abstract class section
  src/site/img/inheritance_collections.png
  src/site/topic14.rst
Labels: content --- mortar_board :mortar_board:

#178 :mortar_board: Lab1
  src/site/img/lab1_empty.png
  src/site/img/lab1_helloworld.png
  src/site/lab1.rst
Labels: content --- mortar_board :mortar_board:

#168 :mortar_board: Topic15 Array implementations of Bag
  src/main/java/ArrayIndexedBag.java
  src/main/java/ArrayIterator.java
  src/main/java/ArraySortedBag.java
  src/main/java/Bag.java
Labels: content --- mortar_board :mortar_board:

#179 :mortar_board: Lab2 Playing with Objects
  src/site/lab2.rst
Labels: content --- mortar_board :mortar_board:

#182 :mortar_board: Topic15 Introduction for array based implementations of bags
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#183 :mortar_board: Topic15 Setup the idea for the array based implementation of the bag
  src/site/img/bag_arrayBag.png
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#187 :mortar_board: Topic15 Finish section on `ArraySortedBag`
  src/main/java/ArraySortedBag.java
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#188 :mortar_board: Topic15 Linked implementation section
  src/site/img/bag_linkedBag.png
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#185 :mortar_board: Topic15 Finish section on ``ArrayIndexedBag``
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#189 :mortar_board: Lab3
  src/site/lab3.rst
Labels: content --- mortar_board :mortar_board:

#186 :mortar_board: Topic15 Start section for ``ArraySortedBag``
  src/main/java/ArraySortedBag.java
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#191 :mortar_board: Topic15 Add download links for tests
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:

#190 :mortar_board: Topic16 Iterators intro
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#194 :new: :mortar_board: Lab3 Add section on testing the stack
  src/site/lab3.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#195 :new: :mortar_board: Lab2 Add additional methods to Lab2
  src/site/lab2.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#193 :bug: :mortar_board: Topic15 Fix ordering of sections and add testing section
  src/site/topic15.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#196 :mortar_board: Lab3 for tests
  src/site/index.rst
  src/site/lab3.rst
  src/site/lab4.rst
Labels: content --- mortar_board :mortar_board:

#198 :mortar_board: Topic19 Sections
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:
