Repository jameshughes89/cs102, pull requests merged in 2021-09, with the labels that each got.

#318 :mortar_board: Topic23 Definition of a Binary Search Tree
  src/site/img/binarysearchtree_base.png
  src/site/img/binarysearchtree_noyes.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#319 :bug::art:Topic23 Move BST image out of note
  src/site/topic23.rst
Labels: typo/bug :bug:, art :art:

#320 :mortar_board: Topic23 Reintroduce boring search through a binary tree
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#321 :bug: :lipstick: fix a bunch of sphinx warnings
  .gitignore
  src/site/lab3.rst
  src/site/lab7.rst
  src/site/topic15.rst
  src/site/topic17.rst
  src/site/topic18.rst
  src/site/topic22.rst
  src/site/topic4.rst
  src/site/topic5.rst
  src/site/topic6.rst
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:

#322 :mortar_board: Topic23 Binary search explaination
  src/site/img/binarysearchtree_binarysearch0.png
  src/site/img/binarysearchtree_binarysearch1.png
  src/site/img/binarysearchtree_binarysearch2.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#323 :mortar_board: Topic23 Break the BST operator section into subsections
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#324 :mortar_board: Topic23 Add download links to BST interface and linked implementation
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#325 :mortar_board: Topic23 Add operator examples
  src/site/img/binarysearchtree_add0.png
  src/site/img/binarysearchtree_add1.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#326 :new: :mortar_board: Topic23 Note on assuming a linked implementation for searching BST
  src/site/topic23.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#328 :art: Topic23 Resize image for the example of adding
  src/site/topic23.rst
Labels: art :art:

#327 :mortar_board: Topic23 Min and remove min operations
  src/site/img/binarysearchtree_removemin0.png
  src/site/img/binarysearchtree_removemin1.png
  src/site/img/binarysearchtree_removemin2.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#329 :mortar_board: Topic23 Finding and/or removing the max
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#330 :bug::art: Topic23 Include the correct images for remove min
  src/site/topic23.rst
Labels: typo/bug :bug:, art :art:

#331 :mortar_board: Topic23 Balanced vs unbalanced or degenerate trees
  src/site/img/binarysearchtree_balance.png
  src/site/img/binarysearchtree_degenerate_gif.gif
  src/site/img/degenerate_gif/degenerate_0.png
  src/site/img/degenerate_gif/degenerate_1.png
  src/site/img/degenerate_gif/degenerate_2.png
  src/site/img/degenerate_gif/degenerate_3.png
  src/site/img/degenerate_gif/degenerate_4.png
  src/site/img/degenerate_gif/degenerate_5.png
  src/site/img/degenerate_gif/degenerate_6.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#332 :mortar_board: Topic23 General remove from a binary search tree
  src/site/img/binarysearchtree_remove0.png
  src/site/img/binarysearchtree_remove1.png
  src/site/img/binarysearchtree_remove2.png
  src/site/img/binarysearchtree_remove3.png
  src/site/img/binarysearchtree_removeuh.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#333 :art: :telescope::lipstick: Topic23 Resize images for remove
  src/site/topic23.rst
Labels: consistency --- telescope :telescope:, formatting --- lipstick :lipstick:, art :art:

#334 :mortar_board: Topic23 Contains & Count
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#335 :art::lipstick: Topic14 Resize various images
  src/site/topic14-careful.rst
  src/site/topic14.rst
Labels: formatting --- lipstick :lipstick:, art :art:

#336 :mortar_board::art: Topic23 Add complexity image to discussion on degenerate
  src/site/img/binarysearchtree_complexity.png
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:, art :art:

#337 :mortar_board::telescope: Topic24 Move files around
  src/site/index.rst
  src/site/topic23.rst
  src/site/topic24.rst
  src/site/topic25.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#338 :mortar_board::bug: Topic24 Constructors and class setup
  src/main/java/LinkedBinarySearchTree.java
  src/site/topic24.rst
  src/test/java/LinkedBinarySearchTreeTest.java
Labels: typo/bug :bug:, content --- mortar_board :mortar_board:

#340 :bug: Topic25 Rename topic24 -> topic25
  src/site/topic25.rst
Labels: typo/bug :bug:

#346 :mortar_board: Topic24 Contains & binary serach
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:

#342 :mortar_board: Topic24 Add
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:

#343 :mortar_board: Topic24 Minimum and Maximum
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:

#345 :bomb::mortar_board: Topic24 Cut traversals section
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:, delete --- bomb :bomb:

#347 :mortar_board: Topic24 removeMin and removeMax
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:

#349 :mortar_board: Topic24 getCount discussion
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:
