Repository jameshughes89/cs102, pull requests merged in 2021-07, with the labels that each got.

#202 :mortar_board: Reorder search topic
  src/site/topic20.rst
  src/site/topic21.rst
  src/site/topic22.rst
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#180 :mortar_board: Topic15 `ArrayIndexedBagTest` added to repo
  src/main/java/ArrayIndexedBag.java
  src/main/java/ArraySortedBag.java
  src/test/java/ArrayIndexedBagTest.java
Labels: content --- mortar_board :mortar_board:

#181 :mortar_board: Topic15 `ArraySortedBagTest` added to repo
  src/main/java/ArraySortedBag.java
  src/test/java/ArraySortedBagTest.java
Labels: content --- mortar_board :mortar_board:

#197 :mortar_board: Topic18 Rename topic and add sections
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#199 :mortar_board: Binary tree interface
  src/main/java/BinaryTree.java
Labels: content --- mortar_board :mortar_board:

#204 :mortar_board: Topic17 `LinkedIterator` class
  src/main/java/LinkedIterator.java
Labels: content --- mortar_board :mortar_board:

#205 :mortar_board: `BinarySearchTree` interface
  src/main/java/BinarySearchTree.java
Labels: content --- mortar_board :mortar_board:

#206 :bug: :mortar_board: Fix a greaterthan/lessthan issue
  src/main/java/ArraySortedBag.java
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#207 :telescope: :mortar_board: Remove `toString` from `BinarySearchTree` interface
  src/main/java/BinarySearchTree.java
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#209 :new: :mortar_board: Topic7 Add warning about head not being a node
  src/site/topic7.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#208 :mortar_board: `LinkedBinarySearchTree` implementation
  src/main/java/BinarySearchTree.java
  src/main/java/LinkedBinarySearchTree.java
  src/test/java/LinkedBinarySearchTreeTest.java
Labels: content --- mortar_board :mortar_board:

#214 :bug: :mortar_board: Topic16 Change wording around for loops and linked structures
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#211 :mortar_board: DON'T add class of search methods to repo
  .gitignore
Labels: content --- mortar_board :mortar_board:

#215 :mortar_board: Topic16 Add description of iterators and iterator interface
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#216 :mortar_board: Topic16 Array Iterator
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#217 :mortar_board: Topic16 Add discussion on `LinkedIterator`
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#220 :mortar_board: Topic16 Examples of using the iterators
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#221 :mortar_board: Add 'warnings' about direction and modifying
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#222 :mortar_board: Topic16 Add notes and examples for Iterable
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#223 :mortar_board: Topic16 Add download links to iterators and tests
  src/site/topic16.rst
Labels: content --- mortar_board :mortar_board:

#218 :mortar_board: Add ArrayIterator tests
  src/test/java/ArrayIteratorTest.java
Labels: content --- mortar_board :mortar_board:

#219 :mortar_board: Add LinkedIterator test
  src/test/java/LinkedIteratorTest.java
Labels: content --- mortar_board :mortar_board:

#224 :bug: Topic16 Fix download links
  src/site/topic16.rst
Labels: typo/bug :bug:

#225 :bug: Fix lab intros
  src/site/lab2.rst
  src/site/lab3.rst
  src/site/lab4.rst
Labels: typo/bug :bug:

#226 :bug: Change project name: Lab3 -> Lab4
  src/site/lab4.rst
Labels: typo/bug :bug:

#229 :mortar_board: Topic18 The high level breakdown of memory
  src/site/img/memory_abstraction.png
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#230 :mortar_board: Topic18 Demonstration of causing a stack overflow
  src/site/img/memory_overflow.png
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#227 :mortar_board: Lab5 --- linked structures
  src/site/index.rst
  src/site/lab5.rst
Labels: content --- mortar_board :mortar_board:

#228 :mortar_board: Topic18 Intro for memory topic
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#231 :bug: Fix various issues
  src/site/index.rst
  src/site/lab3.rst
  src/site/lab5.rst
  src/site/topic3.rst
Labels: typo/bug :bug:

#232 :mortar_board: Topic18 Call stack & frames
  src/site/img/callstack_gif.gif
  src/site/img/callstack_gif/callstack_0.png
  src/site/img/callstack_gif/callstack_1.png
  src/site/img/callstack_gif/callstack_10.png
  src/site/img/callstack_gif/callstack_2.png
  src/site/img/callstack_gif/callstack_3.png
  src/site/img/callstack_gif/callstack_4.png
  src/site/img/callstack_gif/callstack_5.png
  src/site/img/callstack_gif/callstack_6.png
  src/site/img/callstack_gif/callstack_7.png
  src/site/img/callstack_gif/callstack_8.png
  src/site/img/callstack_gif/callstack_9.png
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#233 :mortar_board: Topic18 Heap section
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#234 :mortar_board: Topic18 Garbage collection
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#235 :mortar_board: Topic20 Section layout
  src/site/topic20.rst
Labels: consistency --- telescope :telescope:

#237 :mortar_board: Topic21 Add definitions section
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#238 :mortar_board: Topic22 Add sections for binary tree
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#239 :mortar_board: Topic23 Add binary search tree topic sections
  src/site/topic23.rst
Labels: content --- mortar_board :mortar_board:

#236 :mortar_board: Topic 20 Add intro section
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#240 :mortar_board: Topic24 Add sections for sorting
  src/site/topic24.rst
Labels: content --- mortar_board :mortar_board:

#242 :mortar_board: Lab6
  src/site/lab6.rst
Labels: content --- mortar_board :mortar_board:

#243 :mortar_board: Lab7
  src/site/lab7.rst
Labels: content --- mortar_board :mortar_board:

#245 Lab6
  src/site/lab6.rst
Labels: content --- mortar_board :mortar_board:

#241 :robot: Update gradle-build-deploy.yml
  .github/workflows/gradle-build-deploy.yml
  .github/workflows/gradle-build.yml
Labels: deployment --- robot :robot:

#246 :robot: Remove unzip and update sync dir
  .github/workflows/gradle-build-deploy.yml
Labels: deployment --- robot :robot:

#247 :robot: Change source for aws sync
  .github/workflows/gradle-build-deploy.yml
Labels: deployment --- robot :robot:

#251 :memo: :mortar_board: Asn1 gitignore
  .gitignore
  src/main/java/Assignment1.java
Labels: content --- mortar_board :mortar_board:, documentation --- memo :memo:

#250 :mortar_board: Add links to labs 6 -- 8 to index
  src/site/index.rst
Labels: content --- mortar_board :mortar_board:

#249 :mortar_board: Lab8
  src/site/lab8.rst
Labels: content --- mortar_board :mortar_board:

#252 :memo: :mortar_board: Move A1 solution to a package
  .gitignore
  src/main/java/Assignment1.java
  src/site/asn1.rst
Labels: content --- mortar_board :mortar_board:, documentation --- memo :memo:

#253 :bug: fix typo `'` -> `;`
  src/site/topic2.rst
Labels: typo/bug :bug:

#255 :mortar_board: Topic19 Introduction to recursion
  src/site/img/recursion_line.png
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#256 :mortar_board: Topic18 Resize stack overflow example
  src/site/topic18.rst
Labels: content --- mortar_board :mortar_board:

#258 :mortar_board: :bug: Topic19 Fix backquote position
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#257 :mortar_board: Topic19 Start iterative vs recursive definitions
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#259 :mortar_board: Topic19 Recursive list definition
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#261 :mortar_board: :bug: Topic19 Remove extra space again
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#264 :mortar_board: Topic19 Remove sum section
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#260 :mortar_board: Topic19 Breaking down problems and going 'up' vs 'down'
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#265 :mortar_board: Topic19 Add a few observations about recursion
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#267 :mortar_board: Topic19 Add clarity on recursive functions being 'easy' to write
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#266 :mortar_board: Topic19 Introduce analysis section
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#269 :mortar_board: Topic19 Towers of Hanoi
  src/site/img/recursion_tower.gif
  src/site/img/recursion_tower.png
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#263 :mortar_board: :bug: Topic19 Fix list example again
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#271 :mortar_board: Topci20 Introduction to linear search
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#272 :mortar_board: Topic20 Add iterative linear search
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#275 :telescope: Change markdown titles to be consistent
  src/site/gettingset.rst
  src/site/outline.rst
Labels: consistency --- telescope :telescope:

#274 :mortar_board: Topic20 Recursive linear search
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#268 :mortar_board: Topic19 Fibonacci example with a look at complexity
  src/site/img/recursion_fibonacci.png
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:

#278 🎓 🆕 Move debugging example with Brian C video to memory topic
  src/site/topic18.rst
  src/site/topic19.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#279 :bug: :mortar_board: Topic20 Correct explination of middle average
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#280 :mortar_board: Topic20 Change to needle and haystack in content
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#273 :mortar_board: Topic20 Add search method code to repo
  src/main/java/SearchingMethods.java
  src/test/java/SearchingMethodsTest.java
Labels: content --- mortar_board :mortar_board:

#282 :bug: :mortar_board: Topic20 Fix constant time symbols
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#281 :new: :art: :mortar_board: Topic20 Add linear serach example image and notes
  src/site/img/search_linear.png
  src/site/topic20.rst
Labels: art :art:, content --- mortar_board :mortar_board:, enhancement/new :new:

#284 :mortar_board: Topic20 Iterative binary search
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#283 :mortar_board: Topic20 Introduce binary search
  src/site/img/search_binary.png
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#285 :mortar_board: Topic20 Recursive binary search
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#288 :new: :mortar_board: Topic20 Add helper methods for recursion
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#290 :mortar_board: Topic20 Add download links
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:

#289 :lipstick: :mortar_board: Topic20 Change how recursive binary search parameter values are passed
  src/main/java/SearchingMethods.java
  src/site/topic20.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:, formatting --- lipstick :lipstick:

#291 :mortar_board: Topic21 Introduction to trees
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#292 :mortar_board: Topic21 Definition of a tree
  src/site/img/tree_definition.png
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#293 :mortar_board: Topic21 Node-ish related definitions
  src/site/img/tree_nodes.png
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#296 :new: :mortar_board: Topic22 Add binary tree interface section & download
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#294 :mortar_board: Topic21 Node relationship definitions
  src/site/img/tree_base.png
  src/site/img/tree_subtree_root.png
  src/site/img/tree_subtrees.png
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#295 :mortar_board: Topic21 Definitions related to measurements of a tree
  src/site/img/tree_levels.png
  src/site/img/tree_path.png
  src/site/topic21.rst
Labels: content --- mortar_board :mortar_board:

#297 :new: :mortar_board: Topic22 Add download link to binary tree interface
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:, enhancement/new :new:

#298 :mortar_board: Topc22 Add intro to binary trees
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#299 :mortar_board: Topic22 Binary tree definition
  src/site/img/binarytree_example.png
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#300 :mortar_board: Topic22 Start traversals section
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#301 :mortar_board: Topic22 Preorder traversal subsection
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#302 :mortar_board: Topic22 Inorder traversal subsection
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#303 :mortar_board: Topic22 Postorder traversal subsection
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:

#306 :mortar_board: Topic22 Traversal computational complexity analysis
  src/site/topic22.rst
Labels: content --- mortar_board :mortar_board:
