Repository jameshughes89/cs102, pull requests merged in 2022-03, with the labels that each got.

#489 🐛 Asn2 Fix `DfsMazeSolverTest`
  src/site/data/Assignment2/test/DfsMazeSolverTest.java
Labels: typo/bug :bug:

#490 🆕 Asn2 Add warning about adding JUnit
  src/site/asn2.rst
Labels: enhancement/new :new:

#488 🎓 Asn3 Task Section
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#492 :bug: Asn2 Fix Renfererererer test class name
  src/site/asn2.rst
Labels: typo/bug :bug:

#493 🎓 Asn3 Part 1 --- Read
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#494 🎓 Asn3 Part 2 Early Tests
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#495 🎓 Asn3 Part 5 Putting it Together
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#496 🎓 Asn3 Part 6 Testing Again
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#497 🎓 Asn3 Part 3 Priority Queue
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#498 🎓 Asn3 Part 4 A Star
  src/site/asn3.rst
Labels: content --- mortar_board :mortar_board:

#499 :bug: Asn2 change W -> w
  src/site/asn2.rst
Labels: typo/bug :bug:

#501 🆕 Asn3 Change Assignment Name
  src/site/asn3.rst
Labels: enhancement/new :new:

#500 🎓 Asn3 Add link to assignment on main page
  src/site/index.rst
Labels: content --- mortar_board :mortar_board:

#502 :new: Asn3 Private Methods
  src/site/asn3.rst
Labels: enhancement/new :new:

#505 💄 Asns Titles Format
  src/site/asn2.rst
  src/site/asn3.rst
Labels: formatting --- lipstick :lipstick:

#504 💄 :bug: Asns FAQ Remove Extra Word
  src/site/asn1.rst
  src/site/asn2.rst
  src/site/asn3.rst
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:

#506 🎓 Asn4 Create Description Page
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#507 🆕 Asn4 Add Test Details Back
  src/site/data/Assignment4/test/HuffInternalTest.java
  src/site/data/Assignment4/test/HuffLeafTest.java
  src/site/data/Assignment4/test/HuffNodeComparatorTest.java
  src/site/data/Assignment4/test/HuffmanCodeTest.java
Labels: enhancement/new :new:

#509 🎓 Asn4 Provided Files
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#508 🎓 Asn4 Task
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#512 🎓 Asn4 Part1 Read About Huffman Codes
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#514 🎓 Asn4 Part3 ``HuffmanNodeComparator``
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#513 🎓 Asn4 Part 2 ``HuffmanNode`` classes
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#515 🎓 Asn4 Part6 Testing
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#524 💄 Lab 5 Change `T` -> `Integer` in first method
  src/site/lab5.rst
Labels: formatting --- lipstick :lipstick:

#516 🎓 Asn4 Part5 ``main``
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#521 🎨 🔭 Update ArrayQueue Image
  src/site/img/arrayqueue_3idea0.png
Labels: consistency --- telescope :telescope:, art :art:

#517 🎓 Asn4 Part4 ``HuffmanCode``
  src/site/asn4.rst
Labels: content --- mortar_board :mortar_board:

#518 🎓 Asn4 Add Link to index
  src/site/index.rst
Labels: content --- mortar_board :mortar_board:

#519 🎨 Update LinkedStack Images
  src/site/img/linkedstack0.png
  src/site/img/linkedstack1.png
  src/site/img/linkedstack2.png
  src/site/img/linkedstack3.png
Labels: art :art:

#520 🎨 Update LinkedQueue Images
  src/site/img/linkedqueue0.png
  src/site/img/linkedqueue1.png
  src/site/img/linkedqueue2.png
Labels: art :art:

#525 :bug: Asn4 Fix Link
  src/site/asn4.rst
Labels: typo/bug :bug:

#526 🔭 💄 Change Skeleton
  src/site/asn4.rst
  src/site/lab4.rst
Labels: consistency --- telescope :telescope:, formatting --- lipstick :lipstick:

#527 :art: Lab1 Change where `[]` is in image
  src/site/img/lab1_helloworld.png
Labels: art :art:

#528 🐛:bomb: Maze Remove Update Header
  src/site/data/Assignment2/src/Maze.java
  src/site/data/Assignment3/src/maze/Maze.java
Labels: typo/bug :bug:, delete --- bomb :bomb:

#529 :bug: Topic12 Fix Typesetting
  src/site/topic12.rst
Labels: typo/bug :bug:

#530 :lipstick: Topic12 `expandCapacity` Aside Reorder
  src/site/topic12-expand.rst
Labels: formatting --- lipstick :lipstick:

#531 :lipstick: Topic3 Playing Code Download
  src/main/java/PlayingObjects.java
  src/site/topic3.rst
Labels: formatting --- lipstick :lipstick:

#532 💄 Topic6 Playing Code Download
  src/main/java/PlayingArrayStack.java
  src/site/topic6.rst
Labels: formatting --- lipstick :lipstick:

#533 💄 Topic8 Playing Code Download
  src/main/java/PlayingLinkedStack.java
  src/site/topic8.rst
Labels: formatting --- lipstick :lipstick:

#534 🐛 Stack -> Queue
  src/test/java/LinkedQueueThoroughTest.java
Labels: typo/bug :bug:

#537 🤖 📝 Add dependabot to Repo
  .github/dependabot.yml
Labels: documentation --- memo :memo:, deployment --- robot :robot:

#547 :bug: Topic13 Typo: is -> of
  src/site/topic13.rst
Labels: typo/bug :bug:

#548 🐛 Cpp Pointers Fix Typesetting
  src/site/cpp-pointers.rst
Labels: typo/bug :bug:

#549 :new: 🎓 Cpp Arrays
  src/site/cpp-arrays.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#551 :new: 🎓 Cpp Static Arrays
  src/site/cpp-arrays.rst
  src/site/img/cpp_static_array.png
  src/site/img/cpp_static_array_set.png
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#555 :bug: Topic14 Add New Lines For Formatting
  src/site/topic14.rst
Labels: typo/bug :bug:

#552 🎓 🆕 💩 Cpp Dynamic Arrays
  src/site/cpp-arrays.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#556 :new: 🎓 💩 Add Cpp Arrays to Index
  src/site/index.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#557 💄 Lab7 Add Download Link to Bag
  src/site/lab7.rst
Labels: formatting --- lipstick :lipstick:

#561 :bug: Topic14 it's hasH code
  src/site/topic14.rst
Labels: typo/bug :bug:

#562 :bug: Topic3 Remove Comma
  src/site/topic3.rst
Labels: typo/bug :bug:

#563 :new: :poop: Cpp Topic on References
  src/site/cpp-arrays.rst
  src/site/cpp-references.rst
  src/site/img/cpp-ref.gif
  src/site/img/cpp-ref_pointer.png
  src/site/img/cpp-ref_reference.png
  src/site/img/cpp-ref_regular.png
  src/site/img/cpp-reference_gif/ref0.png
  src/site/img/cpp-reference_gif/ref1.png
  src/site/img/cpp-reference_gif/ref2.png
  src/site/img/cpp-reference_gif/ref3.png
  src/site/index.rst
Labels: enhancement/new :new:

#566 :bug::poop: Cpp Reference Remove extra space
  src/site/cpp-references.rst
Labels: typo/bug :bug:

#569 💄 LinkedIterator Make Field Private
  src/main/java/LinkedIterator.java
Labels: formatting --- lipstick :lipstick:

#570 🐛 Topic16 <Integer> -> <T>
  src/site/topic16.rst
Labels: typo/bug :bug:

#558 :new: :poop: Cpp Objects Topic Friend Class
  src/site/cpp-objects.rst
  src/site/img/cpp_friend.png
  src/site/img/cpp_friend_copy.png
  src/site/img/cpp_friend_pointer.png
  src/site/img/cpp_friend_pointer_copy.png
Labels: enhancement/new :new:

#574 :lipstick: Cpp Arrays Note Move Point to Sentence
  src/site/cpp-arrays.rst
Labels: formatting --- lipstick :lipstick:

#575 :new: Cpp Pointers Add Note on Smart Pointers
  src/site/cpp-pointers.rst
Labels: enhancement/new :new:

#576 Update Method Name
  src/site/asn3.rst
Labels: typo/bug :bug:

#584 :lipstick::bug: Topic19 Cleanup
  src/site/topic19.rst
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:

#586 💄 Lab8 Put Factorial Before Sum
  src/site/lab8.rst
Labels: formatting --- lipstick :lipstick:
