Repository jameshughes89/cs102, pull requests merged in 2023-01, with the labels that each got.

#692 🧑‍💻 Array Sorted Bag --- Clean 🧹
  src/main/java/ArrayIndexedBag.java
  src/main/java/ArraySortedBag.java
  src/main/java/SortedBag.java
  src/test/java/ArrayIndexedBagEqualsTest.java
  src/test/java/ArraySortedBagEqualsTest.java
  src/test/java/ArraySortedBagTest.java
Labels: code content --- technologist :woman_technologist:

#698 :lipstick: :mortar_board: Objects & collections lab --- Clean :broom:
  src/site/labs/objects-collections/objects-collections.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#697 :new: :mortar_board: Unit testing collections topic --- Motivate
  src/site/topics/testing/unit-test-collections.rst
Labels: enhancement/new :new:

#703 :lipstick: Outline --- Change wording under labs section
  src/site/outline/outline.rst
Labels: formatting --- lipstick :lipstick:

#701 :new: :mortar_board: Assignments --- FAQ page
  src/site/assignments/country-catalogue/country-catalogue.rst
  src/site/assignments/faq.rst
  src/site/assignments/huffman-codes/huffman-codes.rst
  src/site/assignments/maze-solver-too/maze-solver-too.rst
  src/site/assignments/maze-solver/maze-solver.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#699 🎓 Assignment 1 --- Clean intro 🧹
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#702 :lipstick: :mortar_board: Assignment 1 --- Clean end bit :broom:
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#700 :lipstick: :mortar_board: Assignment 1 --- Clean country part
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#705 :lipstick: Assignment 1 --- Mention adding junit to class path :microscope:
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: formatting --- lipstick :lipstick:

#706 :bug: :lipstick: Java vs. Python topic --- Fix java example and change warnings to notes
  src/site/topics/java-vs-python/java-vs-python.rst
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:

#707 💄 🎓 Assignment 1 --- Explain `main`
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#711 :mortar_board: Unit Testing Collections Topic --- Motivate a little more :microscope:
  src/site/topics/testing/unit-test-collections.rst
Labels: content --- mortar_board :mortar_board:

#709 :lipstick: :mortar_board: Assignment 1 --- Clean country catalogue description bit
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#710 :mortar_board: Assignment 1 --- Add link to index
  src/site/index.rst
Labels: content --- mortar_board :mortar_board:

#712 :telescope: Assignment 1 --- Rename and number assignments :microscope:
  src/site/assignments/country-catalogue/country-catalogue.rst
  src/site/index.rst
Labels: consistency --- telescope :telescope:

#713 :new: :mortar_board: Unit Testing Collections Topic --- Test empty stack
  src/site/topics/testing/unit-test-collections.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#714 :lipstick: :mortar_board: Intro topic --- Small cleanup :microscope:
  src/site/topics/intro/introduction.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#716 :new: :mortar_board: Hello World Lab --- Warn about Kattis file names
  src/site/labs/hello-world/hello-world.rst
  src/site/labs/hello-world/kattis_name.png
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#717 :lipstick: :mortar_board: Objects & Collections Labs --- Split
  src/site/index.rst
  src/site/labs/objects-collections/collections.rst
  src/site/labs/objects-collections/objects.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#715 :new: :mortar_board: Unit Testing Collections Topic --- Test singleton stack
  src/site/topics/testing/unit-test-collections.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#719 :bug: typo fix for pretend code
  src/site/topics/java-vs-python/java-vs-python.rst
Labels: typo/bug :bug:

#718 :bug: :mortar_board: Unit test topic --- Remove comma :microscope:
  src/site/topics/testing/unit-tests.rst
Labels: typo/bug :bug:

#720 :bomb: :technologist: `ArrayStackTest` --- Remove useless tests
  src/test/java/ArrayStackTest.java
Labels: content --- mortar_board :mortar_board:, code content --- technologist :woman_technologist:

#721 :bomb: :technologist: `ArrayQueueTests` --- Remove useless tests
  src/test/java/ArrayQueueTest.java
Labels: delete --- bomb :bomb:, code content --- technologist :woman_technologist:

#722 :new: :mortar_board: Unit Testing Collections Topic --- Many tests
  src/site/index.rst
  src/site/topics/testing/unit-test-collections.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#725 💄🎓 Java vs Python --- Fix typesetting 🔬
  src/site/topics/java-vs-python/java-vs-python.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#726 :lipstick: :mortar_board: Objects review topic --- Typesetting :microscope:
  src/site/topics/objects-review/objects-review.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#727 :lipstick: :mortar_board: Unit tests lab --- Clean :broom:
  src/site/index.rst
  src/site/labs/unit-tests/unit-tests.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#724 :lipstick: :bug: :technologist: Other Stack, Queues, and Bags --- Change test names
  src/test/java/ArrayIndexedBagTest.java
  src/test/java/ArrayQueueTest.java
  src/test/java/ArraySortedBagTest.java
  src/test/java/LinkedQueueTest.java
  src/test/java/LinkedStackTest.java
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#723 :bug: :lipstick: :technologist: `ArrayStackTest` --- Change test names
  src/test/java/ArrayStackTest.java
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#732 :lipstick: :mortar_board: Stack Topic --- Remove space in interface :microscope:
  src/site/topics/stacks/stack-adt.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#731 :lipstick: :mortar_board: Queue Topic --- Clean :broom:
  src/site/topics/queues/queue-adt.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#730 :lipstick: :telescope: :technologist: `BinaryNode` --- Clean :broom:
  src/main/java/BinaryNode.java
  src/test/java/BinaryNodeTest.java
Labels: consistency --- telescope :telescope:, formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#729 :lipstick: :mortar_board: Algorithm Analysis Topic --- clean :broom:
  src/site/topics/algorithm-analysis/algorithm-analysis.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#737 :lipstick: :technologist: `BinaryNode` --- Update class doc a little more
  src/main/java/BinaryNode.java
Labels: formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#755 :memo: Gitignore --- Ignore playground package :microscope:
  .gitignore
Labels: documentation --- memo :memo:

#738 :new: :mortar_board: Country Catalogue Assignment --- Warn about JUnit 4
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#742 :bug: :mortar_board: Objects Review --- Fix note on null safe equals
  src/site/topics/objects-review/objects-review.rst
Labels: typo/bug :bug:, content --- mortar_board :mortar_board:

#743 :lipstick: :mortar_board: Country Catalogue Assignment --- Warn about infinity
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#744 :lipstick: :telescope: :mortar_board: Early Topics --- Update playing code sections
  src/site/topics/linked-structures/linked-structures.rst
  src/site/topics/objects-review/data-structures-review.rst
  src/site/topics/objects-review/objects-review.rst
  src/site/topics/queues/queue-adt.rst
  src/site/topics/stacks/array-stack.rst
  src/site/topics/stacks/linked-stack.rst
  src/site/topics/stacks/stack-adt.rst
  src/site/topics/testing/unit-test-collections.rst
  src/site/topics/testing/unit-tests.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#736 :bug: 💄 🧑‍💻 `Friend` Class --- Fix & update commented out docs
  src/main/java/Friend.java
  src/site/topics/objects-review/objects-review.rst
Labels: typo/bug :bug:, formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#746 :mortar_board: Test 1 --- Set date in outline :microscope:
  src/site/outline/outline.rst
Labels: content --- mortar_board :mortar_board:

#745 :mortar_board: Country Catalogue Assignment --- Due Date :microscope:
  src/site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#748 :lipstick: :mortar_board: Algorithm analysis amortization aside --- clean :broom:
  src/site/topics/algorithm-analysis/amortized.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#750 💄 🎓 Array Queue --- Clean ideas 1 & 2
  src/site/topics/queues/array-queue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#753 :lipstick: :mortar_board: Unit test topic --- Replace a word :microscope:
  src/site/topics/testing/unit-tests.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#754 :lipstick: :mortar_board: Stack Lab --- Clean :broom:
  src/site/index.rst
  src/site/labs/stacks/stacks.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#757 :mortar_board: Outline --- Add assignment 1 due date :microscope:
  src/site/outline/outline.rst
Labels: content --- mortar_board :mortar_board:

#758 :bug: :mortar_board: Stack ADT Topic --- Fix maze dimension :microscope:
  src/site/topics/stacks/stack-adt.rst
Labels: typo/bug :bug:, content --- mortar_board :mortar_board:

#760 :telescope: :mortar_board: Stack ADT Topic --- Remove period :microscope: :microscope:
  src/site/topics/stacks/stack-adt.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#759 :new: :mortar_board: Stack ADT Topic --- Warn about primitive types & generics
  src/site/topics/stacks/stack-adt.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#764 🎨 🎓 Stack ADT Topic --- Change maze shape
  src/site/topics/stacks/maze.png
  src/site/topics/stacks/maze_animate.gif
  src/site/topics/stacks/maze_gif/maze0.png
  src/site/topics/stacks/maze_gif/maze1.png
  src/site/topics/stacks/maze_gif/maze10.png
  src/site/topics/stacks/maze_gif/maze11.png
  src/site/topics/stacks/maze_gif/maze12.png
  src/site/topics/stacks/maze_gif/maze13.png
  src/site/topics/stacks/maze_gif/maze14.png
  src/site/topics/stacks/maze_gif/maze15.png
  src/site/topics/stacks/maze_gif/maze16.png
  src/site/topics/stacks/maze_gif/maze17.png
  src/site/topics/stacks/maze_gif/maze18.png
  src/site/topics/stacks/maze_gif/maze19.png
  src/site/topics/stacks/maze_gif/maze2.png
  src/site/topics/stacks/maze_gif/maze3.png
  src/site/topics/stacks/maze_gif/maze4.png
  src/site/topics/stacks/maze_gif/maze5.png
  src/site/topics/stacks/maze_gif/maze6.png
  src/site/topics/stacks/maze_gif/maze7.png
  src/site/topics/stacks/maze_gif/maze8.png
  src/site/topics/stacks/maze_gif/maze9.png
Labels: content --- mortar_board :mortar_board:, art :art:

#741 :lipstick: :mortar_board: Linked Queue Topic --- clean :broom:
  src/main/java/PlayingLinkedQueue.java
  src/site/topics/queues/linked-queue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#767 :bug: :technologist: Unit Tests --- Rename setup tests :microscope:
  src/test/java/ArrayIndexedBagTest.java
  src/test/java/ArrayQueueTest.java
  src/test/java/ArraySortedBagTest.java
  src/test/java/LinkedQueueTest.java
Labels: typo/bug :bug:, code content --- technologist :woman_technologist:

#769 :lipstick: :mortar_board: Array Queue Topic --- Clean idea 3 :broom:
  src/site/topics/queues/array-queue.rst
  src/site/topics/queues/arrayqueue_third_idea0.png
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#770 :lipstick: :mortar_board: Array Queue Topic --- Clean more :broom:
  src/main/java/PlayingArrayQueue.java
  src/site/topics/queues/array-queue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#771 :bomb: :mortar_board: Array Queue Topic --- Remove expand capacity warning
  src/site/topics/queues/array-queue.rst
Labels: content --- mortar_board :mortar_board:, delete --- bomb :bomb:

#772 🎓 Array Queue --- Add question marks to question 🔬
  src/site/topics/queues/array-queue.rst
Labels: content --- mortar_board :mortar_board:

#773 💄 🎓 Array Stack Topic --- Change "looped" to "wrapped" 🔬
  src/site/topics/queues/array-queue.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#774 🆕 🎓 Array Queue Topic --- Discuss `equals`
  src/site/topics/queues/array-queue.rst
Labels: enhancement/new :new:, content --- mortar_board :mortar_board:

#775 :bug: :mortar_board: Data Structures Review --- Fix test class download link name
  src/site/topics/objects-review/data-structures-review.rst
Labels: typo/bug :bug:, content --- mortar_board :mortar_board:

#776 :lipstick: :mortar_board: `expandCapacity` aside --- clean
  src/site/topics/queues/expand-capacity.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#777 :lipstick: :woman_technologist: Use `size()` where it makes sense
  src/main/java/ArrayQueue.java
  src/main/java/ArrayStack.java
  src/main/java/ContactList.java
  src/main/java/LinkedQueue.java
Labels: formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#780 :telescope: :mortar_board: Stack ADT Topic --- Remove ".java" from download link
  src/site/topics/stacks/stack-adt.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#782 :telescope: :mortar_board: Stack ADT Topic --- Remove `public` from interface examples
  src/site/topics/stacks/stack-adt.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:

#781 :lipstick: :mortar_board: Stack ADT Topic --- Pseudocode -> Algorithm
  src/site/topics/stacks/stack-adt.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#783 :lipstick: :mortar_board: Bag ADT Topic --- Clean :broom:
  src/site/topics/bags/bag-adt.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#787 :lipstick: :mortar_board: DFS Maze Solver --- Clean description :broom:
  src/site/assignments/maze-solver/maze-solver.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#788 :bug: :mortar_board: Unit testing collections topic --- Add missing call and fix typos
  src/site/topics/testing/unit-test-collections.rst
Labels: typo/bug :bug:, content --- mortar_board :mortar_board:

#790 💄 🎓 Linked Structure Lab --- Clean
  src/site/labs/linked-structures/linked-structures.rst
Labels: formatting --- lipstick :lipstick:

#791 💄 🎓 Queue Lab --- Clean 🧹
  src/site/labs/queues/queues.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#792 💄 🎓 Sorted Bag Lab --- Clean 🧹
  src/site/labs/sorted-bags/sorted-bags.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#793 :lipstick: :technologist: Binary Tree & BST Interface --- clean
  src/main/java/BinarySearchTree.java
  src/main/java/BinaryTree.java
  src/main/java/LinkedBinarySearchTree.java
  src/test/java/LinkedBinarySearchTreeTest.java
Labels: formatting --- lipstick :lipstick:, code content --- technologist :woman_technologist:

#794 :lipstick: :technologist: Bag Interfaces --- Clean a little more
  src/main/java/ArrayIndexedBag.java
  src/main/java/ArraySortedBag.java
  src/main/java/Bag.java
  src/main/java/IndexedBag.java
  src/main/java/SortedBag.java
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:
